import type {
  Citizen,
  Animal,
  LandRecord,
  Document,
  Dispute,
  Notification,
  AuditLog,
  User,
  DashboardStats,
  ActivityItem,
  ChartDataPoint,
  ResidencyRequest,
} from "@/types/entities.types";

const now = new Date();
const daysAgo = (days: number) =>
  new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_USERS: User[] = [
  {
    id: "c0000001-0001-4001-8001-000000000001",
    email: "admin@vdarvs.gov.ls",
    fullName: "Thabo Mokoena",
    role: "administrator",
    district: "Maseru",
    phone: "+266 5888 1000",
    createdAt: daysAgo(365),
  },
  {
    id: "c0000001-0001-4001-8001-000000000002",
    email: "chief.masianokeng@vdarvs.gov.ls",
    fullName: "Chief Letsie Ramokoatsi",
    role: "village_chief",
    village: "Masianokeng",
    district: "Maseru",
    chiefId: "a0000001-0001-4001-8001-000000000001",
    phone: "+266 5888 2001",
    createdAt: daysAgo(300),
  },
  {
    id: "c0000001-0001-4001-8001-000000000003",
    email: "staff.masianokeng@vdarvs.gov.ls",
    fullName: "Mpho Seoli",
    role: "village_staff",
    village: "Masianokeng",
    district: "Maseru",
    phone: "+266 5888 3001",
    createdAt: daysAgo(200),
  },
  {
    id: "c0000001-0001-4001-8001-000000000004",
    email: "district.maseru@vdarvs.gov.ls",
    fullName: "Lerato Khumalo",
    role: "district_officer",
    district: "Maseru",
    phone: "+266 5888 4001",
    createdAt: daysAgo(250),
  },
  {
    id: "c0000001-0001-4001-8001-000000000005",
    email: "citizen@example.ls",
    fullName: "Palesa Molapo",
    role: "citizen",
    village: "Masianokeng",
    district: "Maseru",
    phone: "+266 5888 5001",
    createdAt: daysAgo(30),
  },
];

export const MOCK_CHIEFS = [
  {
    id: "a0000001-0001-4001-8001-000000000001",
    name: "Chief Letsie Ramokoatsi",
    village: "Masianokeng",
    district: "Maseru",
  },
  {
    id: "a0000001-0001-4001-8001-000000000002",
    name: "Chief Motlalepula Tsolo",
    village: "Ha Tsolo",
    district: "Maseru",
  },
  {
    id: "a0000001-0001-4001-8001-000000000003",
    name: "Chief 'Mamohato Khumalo",
    village: "Ha Ramokoatsi",
    district: "Berea",
  },
];

export const MOCK_CITIZENS: Citizen[] = [
  {
    id: "cit-1",
    nationalId: "LS-2001-004521",
    firstName: "Palesa",
    lastName: "Molapo",
    dateOfBirth: "1995-03-14",
    gender: "female",
    phone: "+266 5888 5001",
    email: "palesa.molapo@example.ls",
    address: {
      village: "Masianokeng",
      communityCouncil: "Maseru Central",
      district: "Maseru",
      poBox: "P.O. Box 1234",
    },
    chiefId: "a0000001-0001-4001-8001-000000000001",
    verificationStatus: "verified",
    status: "approved",
    registeredAt: daysAgo(28),
    updatedAt: daysAgo(5),
  },
  {
    id: "cit-2",
    nationalId: "LS-1988-002134",
    firstName: "Thabo",
    lastName: "Mokoena",
    dateOfBirth: "1988-07-22",
    gender: "male",
    phone: "+266 5888 5012",
    address: {
      village: "Ha Tsolo",
      communityCouncil: "Maseru Central",
      district: "Maseru",
    },
    chiefId: "chief-2",
    verificationStatus: "verified",
    status: "approved",
    registeredAt: daysAgo(60),
    updatedAt: daysAgo(10),
  },
  {
    id: "cit-3",
    nationalId: "LS-2003-007891",
    firstName: "Lerato",
    lastName: "Khumalo",
    dateOfBirth: "2003-11-05",
    gender: "female",
    phone: "+266 5888 5023",
    address: {
      village: "Ha Ramokoatsi",
      communityCouncil: "Teyateyaneng",
      district: "Berea",
      poBox: "P.O. Box 567",
    },
    chiefId: "chief-3",
    verificationStatus: "pending",
    status: "pending",
    registeredAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "cit-4",
    nationalId: "LS-1975-001002",
    firstName: "Mpho",
    lastName: "Seoli",
    dateOfBirth: "1975-01-18",
    gender: "male",
    phone: "+266 5888 5034",
    address: {
      village: "Masianokeng",
      communityCouncil: "Maseru Central",
      district: "Maseru",
    },
    chiefId: "a0000001-0001-4001-8001-000000000001",
    verificationStatus: "verified",
    status: "approved",
    registeredAt: daysAgo(120),
    updatedAt: daysAgo(20),
  },
  {
    id: "cit-5",
    nationalId: "LS-1999-005678",
    firstName: "Karabo",
    lastName: "Ntšo",
    dateOfBirth: "1999-09-30",
    gender: "male",
    phone: "+266 5888 5045",
    address: {
      village: "Hlotse",
      communityCouncil: "Hlotse",
      district: "Leribe",
    },
    chiefId: "a0000001-0001-4001-8001-000000000001",
    verificationStatus: "unverified",
    status: "draft",
    registeredAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "cit-6",
    nationalId: "LS-1992-003456",
    firstName: "'Mamohato",
    lastName: "Lerotholi",
    dateOfBirth: "1992-04-12",
    gender: "female",
    phone: "+266 5888 5056",
    address: {
      village: "Maputsoe",
      communityCouncil: "Maputsoe",
      district: "Leribe",
      poBox: "P.O. Box 890",
    },
    chiefId: "a0000001-0001-4001-8001-000000000001",
    verificationStatus: "verified",
    status: "approved",
    registeredAt: daysAgo(90),
    updatedAt: daysAgo(15),
  },
];

export const MOCK_ANIMALS: Animal[] = [
  {
    id: "ani-1",
    tagNumber: "LS-C-2024-001",
    species: "cattle",
    breed: "Afrikaner",
    ownerId: "cit-1",
    ownerName: "Palesa Molapo",
    village: "Masianokeng",
    district: "Maseru",
    registeredAt: daysAgo(20),
    status: "approved",
  },
  {
    id: "ani-2",
    tagNumber: "LS-S-2024-042",
    species: "sheep",
    breed: "Merino",
    ownerId: "cit-2",
    ownerName: "Thabo Mokoena",
    village: "Ha Tsolo",
    district: "Maseru",
    registeredAt: daysAgo(45),
    status: "approved",
  },
  {
    id: "ani-3",
    tagNumber: "LS-G-2024-018",
    species: "goat",
    breed: "Boer",
    ownerId: "cit-4",
    ownerName: "Mpho Seoli",
    village: "Masianokeng",
    district: "Maseru",
    registeredAt: daysAgo(10),
    status: "pending",
  },
  {
    id: "ani-4",
    tagNumber: "LS-C-2024-002",
    species: "cattle",
    breed: "Bonsmara",
    ownerId: "cit-6",
    ownerName: "'Mamohato Lerotholi",
    village: "Maputsoe",
    district: "Leribe",
    registeredAt: daysAgo(30),
    status: "approved",
  },
];

export const MOCK_LAND: LandRecord[] = [
  {
    id: "land-1",
    parcelNumber: "MSR-MK-001",
    ownerId: "cit-1",
    ownerName: "Palesa Molapo",
    village: "Masianokeng",
    communityCouncil: "Maseru Central",
    district: "Maseru",
    landType: "residential",
    sizeHectares: 0.25,
    chiefId: "a0000001-0001-4001-8001-000000000001",
    status: "approved",
    registeredAt: daysAgo(25),
    description: "Family homestead near the village centre",
  },
  {
    id: "land-2",
    parcelNumber: "MSR-HT-014",
    ownerId: "cit-2",
    ownerName: "Thabo Mokoena",
    village: "Ha Tsolo",
    communityCouncil: "Maseru Central",
    district: "Maseru",
    landType: "agricultural",
    sizeHectares: 1.5,
    chiefId: "chief-2",
    status: "approved",
    registeredAt: daysAgo(55),
  },
  {
    id: "land-3",
    parcelNumber: "BER-HR-007",
    ownerId: "cit-3",
    ownerName: "Lerato Khumalo",
    village: "Ha Ramokoatsi",
    communityCouncil: "Teyateyaneng",
    district: "Berea",
    landType: "grazing",
    sizeHectares: 3.0,
    chiefId: "chief-3",
    status: "under_review",
    registeredAt: daysAgo(5),
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc-1",
    referenceNumber: "VDARVS-RC-2024-0001",
    type: "residency_certificate",
    title: "Residency Certificate",
    citizenId: "cit-1",
    citizenName: "Palesa Molapo",
    village: "Masianokeng",
    district: "Maseru",
    status: "approved",
    issuedAt: daysAgo(5),
    requestedAt: daysAgo(10),
    approvedBy: "Chief Letsie Ramokoatsi",
  },
  {
    id: "doc-2",
    referenceNumber: "VDARVS-LT-2024-0003",
    type: "land_title",
    title: "Land Title Certificate",
    citizenId: "cit-2",
    citizenName: "Thabo Mokoena",
    village: "Ha Tsolo",
    district: "Maseru",
    status: "approved",
    issuedAt: daysAgo(15),
    requestedAt: daysAgo(20),
    approvedBy: "Chief Motlalepula Tsolo",
  },
  {
    id: "doc-3",
    referenceNumber: "VDARVS-AP-2024-0012",
    type: "animal_permit",
    title: "Animal Registration Permit",
    citizenId: "cit-4",
    citizenName: "Mpho Seoli",
    village: "Masianokeng",
    district: "Maseru",
    status: "pending",
    requestedAt: daysAgo(2),
  },
  {
    id: "doc-4",
    referenceNumber: "VDARVS-BR-2024-0008",
    type: "birth_record",
    title: "Birth Record Certificate",
    citizenId: "cit-3",
    citizenName: "Lerato Khumalo",
    village: "Ha Ramokoatsi",
    district: "Berea",
    status: "under_review",
    requestedAt: daysAgo(3),
  },
];

export const MOCK_DISPUTES: Dispute[] = [
  {
    id: "disp-1",
    caseNumber: "DSP-2024-001",
    title: "Boundary dispute between Molapo and Seoli families",
    description:
      "Disagreement over the boundary line between two adjacent homesteads in Masianokeng.",
    complainantId: "cit-1",
    complainantName: "Palesa Molapo",
    respondentName: "Mpho Seoli",
    village: "Masianokeng",
    district: "Maseru",
    chiefId: "a0000001-0001-4001-8001-000000000001",
    category: "boundary",
    status: "under_review",
    filedAt: daysAgo(7),
  },
  {
    id: "disp-2",
    caseNumber: "DSP-2024-002",
    title: "Livestock grazing rights on communal land",
    description:
      "Dispute over grazing access to communal land near Ha Tsolo.",
    complainantId: "cit-2",
    complainantName: "Thabo Mokoena",
    respondentName: "Karabo Ntšo",
    village: "Ha Tsolo",
    district: "Maseru",
    chiefId: "chief-2",
    category: "livestock",
    status: "pending",
    filedAt: daysAgo(4),
  },
  {
    id: "disp-3",
    caseNumber: "DSP-2023-045",
    title: "Land inheritance dispute",
    description: "Family dispute over inheritance of agricultural land parcel.",
    complainantId: "cit-6",
    complainantName: "'Mamohato Lerotholi",
    respondentName: "Family Council",
    village: "Maputsoe",
    district: "Leribe",
    chiefId: "a0000001-0001-4001-8001-000000000001",
    category: "land",
    status: "approved",
    filedAt: daysAgo(60),
    resolvedAt: daysAgo(30),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    userId: "user-chief-1",
    title: "New residency verification request",
    message: "Lerato Khumalo has submitted a residency verification request for Ha Ramokoatsi.",
    type: "action",
    read: false,
    createdAt: daysAgo(1),
    href: "/residency",
  },
  {
    id: "notif-2",
    userId: "user-chief-1",
    title: "Document pending approval",
    message: "Animal Registration Permit for Mpho Seoli requires your endorsement.",
    type: "warning",
    read: false,
    createdAt: daysAgo(2),
    href: "/documents",
  },
  {
    id: "notif-3",
    userId: "user-staff-1",
    title: "New citizen registration",
    message: "Karabo Ntšo has been registered in Hlotse, pending verification.",
    type: "info",
    read: true,
    createdAt: daysAgo(1),
    href: "/citizens",
  },
  {
    id: "notif-4",
    userId: "user-admin",
    title: "System audit completed",
    message: "Monthly audit log review completed for Maseru district.",
    type: "success",
    read: true,
    createdAt: daysAgo(5),
    href: "/audit-logs",
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "audit-1",
    userId: "user-chief-1",
    userName: "Chief Letsie Ramokoatsi",
    action: "APPROVE",
    entity: "citizen",
    entityId: "cit-1",
    details: "Approved residency verification for Palesa Molapo",
    village: "Masianokeng",
    district: "Maseru",
    createdAt: daysAgo(5),
  },
  {
    id: "audit-2",
    userId: "user-staff-1",
    userName: "Mpho Seoli",
    action: "CREATE",
    entity: "citizen",
    entityId: "cit-5",
    details: "Registered new citizen Karabo Ntšo",
    village: "Hlotse",
    district: "Leribe",
    createdAt: daysAgo(1),
  },
  {
    id: "audit-3",
    userId: "user-admin",
    userName: "Thabo Mokoena",
    action: "UPDATE",
    entity: "settings",
    entityId: "system",
    details: "Updated notification preferences for Maseru district",
    district: "Maseru",
    createdAt: daysAgo(3),
  },
  {
    id: "audit-4",
    userId: "user-chief-1",
    userName: "Chief Letsie Ramokoatsi",
    action: "CREATE",
    entity: "dispute",
    entityId: "disp-1",
    details: "Opened boundary dispute case DSP-2024-001",
    village: "Masianokeng",
    district: "Maseru",
    createdAt: daysAgo(7),
  },
];

export const MOCK_RESIDENCY_REQUESTS: ResidencyRequest[] = [
  {
    id: "res-1",
    citizenId: "cit-3",
    citizenName: "Lerato Khumalo",
    nationalId: "LS-2003-007891",
    village: "Ha Ramokoatsi",
    district: "Berea",
    chiefId: "chief-3",
    status: "pending",
    requestedAt: daysAgo(3),
  },
  {
    id: "res-2",
    citizenId: "cit-5",
    citizenName: "Karabo Ntšo",
    nationalId: "LS-1999-005678",
    village: "Hlotse",
    district: "Leribe",
    chiefId: "a0000001-0001-4001-8001-000000000001",
    status: "pending",
    requestedAt: daysAgo(1),
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalCitizens: MOCK_CITIZENS.length,
  pendingVerifications: MOCK_RESIDENCY_REQUESTS.filter(
    (r) => r.status === "pending",
  ).length,
  activeDisputes: MOCK_DISPUTES.filter(
    (d) => d.status !== "approved" && d.status !== "archived",
  ).length,
  documentsIssued: MOCK_DOCUMENTS.filter((d) => d.status === "approved").length,
  registeredAnimals: MOCK_ANIMALS.length,
  landParcels: MOCK_LAND.length,
  pendingApprovals: [
    ...MOCK_DOCUMENTS,
    ...MOCK_DISPUTES,
    ...MOCK_ANIMALS,
  ].filter((r) => r.status === "pending" || r.status === "under_review").length,
};

export const MOCK_ACTIVITIES: ActivityItem[] = [
  {
    id: "act-1",
    type: "verification",
    title: "Residency verified",
    description: "Palesa Molapo verified in Masianokeng",
    timestamp: daysAgo(5),
    status: "approved",
  },
  {
    id: "act-2",
    type: "registration",
    title: "New citizen registered",
    description: "Karabo Ntšo registered in Hlotse",
    timestamp: daysAgo(1),
    status: "pending",
  },
  {
    id: "act-3",
    type: "document",
    title: "Document issued",
    description: "Land Title Certificate issued to Thabo Mokoena",
    timestamp: daysAgo(15),
    status: "approved",
  },
  {
    id: "act-4",
    type: "dispute",
    title: "Dispute filed",
    description: "Boundary dispute opened in Masianokeng",
    timestamp: daysAgo(7),
    status: "under_review",
  },
  {
    id: "act-5",
    type: "animal",
    title: "Animal registered",
    description: "Cattle LS-C-2024-001 registered to Palesa Molapo",
    timestamp: daysAgo(20),
    status: "approved",
  },
];

export const MOCK_CHART_DATA: ChartDataPoint[] = [
  { month: "Jan", citizens: 12, documents: 8, disputes: 2 },
  { month: "Feb", citizens: 18, documents: 12, disputes: 1 },
  { month: "Mar", citizens: 15, documents: 10, disputes: 3 },
  { month: "Apr", citizens: 22, documents: 15, disputes: 2 },
  { month: "May", citizens: 28, documents: 18, disputes: 4 },
  { month: "Jun", citizens: 6, documents: 4, disputes: 2 },
];
